### ISSUE TITLE
Email validate

### ISSUE THREAD

**Issue by naresh-knovator** [implerhq/impler.io#271] opened 2023-06-07 05:45 UTC
**Describe the bug**
Email must be valid error whenever i import bulk user.

**To Reproduce**
1. Go to bulk import and select file
2. Click on see maping
3. Click on Review Data 

**Expected behavior**
validate email proper.

**Screenshots**
![image](https://github.com/implerhq/impler.io/assets/50201755/420dd12e-1428-4637-a779-181939c5223b)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome]

**Comment by chavda-bhavik** [comment] 2023-07-04 09:15
@naresh-knovator Closing the issue due to not being able to reproduce it. Feel free to share a sample file if you still face the issue.

**Closed by chavda-bhavik** 2023-07-04 09:15 UTC
Labels: bug, citical
